# Generated by Django 5.1.6 on 2025-05-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('strategy', models.CharField(max_length=50)),
                ('use_sentiment', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('in_position', models.BooleanField(default=False)),
                ('position_side', models.CharField(blank=True, max_length=10, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
