# Generated by Django 5.1.6 on 2025-05-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0002_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='leverage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='trade_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
