# Generated by Django 5.1.6 on 2025-05-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0003_wishlistitem_leverage_wishlistitem_trade_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('target_price', models.FloatField()),
                ('condition', models.CharField(choices=[('above', 'Price above'), ('below', 'Price below')], max_length=10)),
                ('email', models.EmailField(default='swapnilverma00007@gmail.com', max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
